### ISSUE TITLE
Browser security settings prevent the correct Referer header from being set

### ISSUE THREAD

**Issue by iliana** [tdfischer/under-construction#2]
See https://ianweller.org/ and how it says the current page is "home".

Network console in Firefox shows the request header being sent is `Referer: https://tdfischer.github.io/under-construction/embed.html`. It seems to work fine in Chrome and MS Edge though.

Maybe a workaround by sending the intended URL in a query string argument would work?

**Comment by iliana** [comment]
Wait, never mind. I have `network.http.referer.spoofSource` set to true in my browser config. :100:

**Comment by emilyhorsman** [comment]
+🍕
